version: '3.9'

services:
  postgres:
    image: postgres:14-alpine3.15
    ports:
      - 5432:5432
    container_name: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pcpapi
    networks:
      - backend
networks:
  backend:
    external: false
    name: backend
    driver: bridge