services:
  api:
   image: pcp
   container_name: pcp
   ports:
     - ${APP_PORT}:${APP_PORT}
     - ${DEBUG_PORT}:${DEBUG_PORT}
   depends_on:
     - postgres
   environment:
     - QUARKUS_LAUNCH_DEVMODE=true
     - JAVA_DEBUG=true
     - JAVA_DEBUG_PORT=*:${DEBUG_PORT}
  postgres:
    container_name: postgres
    image: postgres:17.0-alpine3.20
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pcp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
