services:
  api:
   image: pcp-api
   ports:
     - 8080:8080
   container_name: pcp-api
   networks:
     - backend
   depends_on:
     - postgres
  postgres:
    container_name: postgres
    image: postgres:17.0-alpine3.20
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pcpapi
    networks:
      - backend
networks:
  backend:
    external: false
    name: backend
    driver: bridge
