services:
  postgres:
    container_name: postgres-erp
    image: postgres:17.0-alpine3.20
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=erp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.68.0
    ports:
      - 4318:4318
      - 16686:16686
    environment:
      - COLLECTOR_OTLP_ENABLED=true
